[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cidaren"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "certifi>=2024.8.30",
    "flask>=3.1,<4",
    "mitmproxy==11.0.2",
    "requests>=2.32,<3",
]

[project.scripts]
cidaren = "cidaren.web:main"

[tool.setuptools]
packages = ["cidaren"]

[tool.setuptools.package-data]
cidaren = ["bank.json"]
